name: Test matrix
on:
  pull_request:
    types:
      - opened
    paths:
      - ".github/workflows/**"
      - ".github/CODEOWNERS"
      - "package*.json"

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github) }}'
