name: Upload data
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: The job has succeeded
        run: echo ${{ddd}}

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: The job has succeeded
        run: echo "job2"

  job3:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: The job has succeeded
        run: echo "job3"
