name: Upload data
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: The job has succeeded
        run: echo "job1"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: The job has succeeded
        run: echo "job2"

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: The job has succeeded
        run: echo "job3"

  job4:
    runs-on: ubuntu-latest
    steps:
      - name: The job has succeeded
        run: echo "job4"
