name: Upload data
on: push

jobs:
  print-tag:
    runs-on: ubuntu-latest

    steps:
      - name: The job has succeeded
        if: ${{ success() }}
        run: echo "sucess"

      - name: The job has always
        if: ${{ always() }}
        run: echo "always"
