name: Test matrix
on:
  pull_request:
    branches:
      - main
      - "mona/octocat"
      - "releases/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump secret context
        run: echo '${{ toJSON(secrets) }}'
