name: GitHub Actions Demo
on: [push]
jobs:
  test-tunnel:
    runs-on: ubuntu-latest
    steps:
      - name: Start Tunnel
        uses: LambdaTest/LambdaTest-tunnel-action@v1
        id: tunnel
        with:
          user: ${{ secrets.LT_EMAIL }}
          accessKey: ${{ secrets.LT_ACCESS_KEY }}
          tunnelName: "32736138-c02f-440e-8fb9-5d1d4f6221f3"
      - run: npm test
      - name: Export Tunnel Logs for debugging
        uses: actions/upload-artifact@v2
        with:
          name: tunnel_logs
          path: ${{ steps.tunnel.outputs.logFileName }}
