name: Context testing
on: pull_request

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump Environment context
        id: github_env_step
        run: echo '${{ toJSON(env) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump secrets context
        run: echo '${{ toJSON(secrets) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - name: Dump needs context
        run: echo '${{ toJSON(needs) }}'
      - name: Dump inputs context
        run: echo '${{ toJSON(inputs) }}'
