name: Node.js CI
on: push
env:
  DAY_OF_WEEK: Monday
inputs:
  file-path: # id of input
    description: "Path to test script"
    required: true
    default: "test-file.js"
outputs:
  results-file: # id of output
    description: "Path to results file"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo $DAY_OF_WEEK
